{
 "title": "FABview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Last update", "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 } },
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 20, "x": 2, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Thin Films T",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{place=\"thin films\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thin Films R.H.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{place=\"thin films\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lithography T",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{place=\"lithography\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lithography R.H.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{place=\"lithography\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adv. Lithography T",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{place=\"advanced lithography\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adv. Lithography R.H.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{place=\"advanced lithography\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature{place=\"thin films\"}",
     "legendFormat": "Thin Films"
    },
    {
     "expr": "temperature{place=\"lithography\"}",
     "legendFormat": "Lithography"
    },
    {
     "expr": "temperature{place=\"advanced lithography\"}",
     "legendFormat": "Adv. Lithography"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "humidity{place=\"thin films\"}",
     "legendFormat": "Thin Films"
    },
    {
     "expr": "humidity{place=\"lithography\"}",
     "legendFormat": "Lithography"
    },
    {
     "expr": "humidity{place=\"advanced lithography\"}",
     "legendFormat": "Adv. Lithography"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Pa" } },
   "targets": [
    {
     "expr": "pressure{place=\"thin films\"} + 0",
     "legendFormat": "Thin Films"
    },
    {
     "expr": "pressure{place=\"lithography\"} + -35",
     "legendFormat": "Lithography"
    },
    {
     "expr": "pressure{place=\"advanced lithography\"}",
     "legendFormat": "Adv. Lithography"
    }
   ]
  },
  {
   "title": "Thin Films",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "temperature", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Relative Humidity",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "humidity{place=\"thin films\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "temperature{place=\"thin films\"}",
       "legendFormat": "Temperature"
      }
     ]
    },
    {
     "title": "Relative Humidity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "humidity{place=\"thin films\"}",
       "legendFormat": "R.H."
      }
     ]
    }
   ]
  },
  { "title": "Lithography", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{place=\"lithography\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{place=\"lithography\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature{place=\"lithography\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "humidity{place=\"lithography\"}",
     "legendFormat": "R.H."
    }
   ]
  },
  {
   "title": "Adv. Lithography",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "temperature{place=\"advanced lithography\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relative Humidity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "humidity{place=\"advanced lithography\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "temperature{place=\"advanced lithography\"}",
       "legendFormat": "Temperature"
      }
     ]
    },
    {
     "title": "Relative Humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "humidity{place=\"advanced lithography\"}",
       "legendFormat": "R.H."
      }
     ]
    }
   ]
  }
 ]
}