version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: 1000:1000  
    environment:
     - GF_SERVER_DOMAIN=https://www.example.com
     - GF_SERVER_ROOT_URL=https://www.example.com/grafana
     - GF_SERVER_SERVE_FROM_SUB_PATH=true
     - GF_AUTH_PROXY_AUTO_SIGN_UP=false
     - GF_AUTH_PROXY_ENABLED=true
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - './data:/var/lib/grafana'
    network_mode: prometheus
